/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pop3.client;

public class App {
    public String getGreeting() {
        return "[POP3 Client] Welcome to POP3 Client.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
