/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ftp.client;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Scanner scanner = new Scanner(System.in);
        String in = scanner.nextLine();
        System.out.println(in);
    }

    public String getGreeting() {
        return "Hello world.";
    }
}
