/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package network.download;

import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;
import java.nio.channels.Channels;
import java.nio.channels.FileChannel;
import java.nio.channels.ReadableByteChannel;

public class App {
    private static String myUrl;
    private static String myFileName;
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());
        myUrl = "https://i.loli.net/2018/11/18/5bf11bc42a1d3.jpg";
        myFileName = "C:\\Users\\Garvey\\Pictures\\1.jpg";
        try {
            downloadWithJavaNIO();
        } catch(IOException e) {
            e.printStackTrace();
        }
    }

    public static void downloadWithJavaNIO () throws IOException {
        URL url = new URL(myUrl);
        ReadableByteChannel readableByteChannel = Channels.newChannel(url.openStream());
        FileOutputStream fileOutputStream = new FileOutputStream(myFileName);
        FileChannel fileChannel = fileOutputStream.getChannel();
        fileChannel.transferFrom(readableByteChannel, 0, Long.MAX_VALUE);
        fileOutputStream.close();
        readableByteChannel.close();
    }
}
